#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  write_linux_runner_env.sh --output /path/to/tvectorblur-runner.env \
    --nuke-root 16.0=/opt/Nuke16.0v9 \
    [--nuke-root 17.0=/opt/Nuke17.0v1] \
    [--cuda-root /usr/local/cuda]

Writes environment variables consumed by the GitHub self-hosted Linux runner:
  NUKE_<major>_<minor>_ROOT
  NUKE_<major>_<minor>_EXECUTABLE
  CUDA_HOME
  PATH
  LD_LIBRARY_PATH
EOF
}

OUTPUT=""
CUDA_ROOT=""
declare -a NUKE_ROOTS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    --nuke-root)
      NUKE_ROOTS+=("$2")
      shift 2
      ;;
    --cuda-root)
      CUDA_ROOT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${OUTPUT}" || ${#NUKE_ROOTS[@]} -eq 0 ]]; then
  usage >&2
  exit 1
fi

if [[ -z "${CUDA_ROOT}" ]]; then
  if command -v nvcc >/dev/null 2>&1; then
    CUDA_ROOT="$(cd "$(dirname "$(command -v nvcc)")/.." && pwd)"
  else
    CUDA_ROOT="/usr/local/cuda"
  fi
fi

mkdir -p "$(dirname "${OUTPUT}")"

{
  echo "# Generated by work/scripts/write_linux_runner_env.sh"
  echo "# shellcheck shell=sh"
  echo "CUDA_HOME=${CUDA_ROOT}"
  echo "PATH=${CUDA_ROOT}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  echo "LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:${CUDA_ROOT}/extras/CUPTI/lib64"

  for entry in "${NUKE_ROOTS[@]}"; do
    version="${entry%%=*}"
    root="${entry#*=}"

    if [[ -z "${version}" || -z "${root}" || "${version}" == "${root}" ]]; then
      echo "Invalid --nuke-root entry: ${entry}" >&2
      exit 1
    fi

    if [[ ! -d "${root}" ]]; then
      echo "Nuke root does not exist: ${root}" >&2
      exit 1
    fi

    version_key="${version//./_}"
    executable="${root}/Nuke${version}"
    if [[ ! -x "${executable}" ]]; then
      echo "Expected Nuke executable not found: ${executable}" >&2
      exit 1
    fi

    echo "NUKE_${version_key}_ROOT=${root}"
    echo "NUKE_${version_key}_EXECUTABLE=${executable}"
  done
} > "${OUTPUT}"

echo "Wrote ${OUTPUT}"
